FROM busybox as builder
ARG ARCH
COPY ./dist /dist
RUN mkdir -p /opt/rust-tools/bin
RUN for i in `find /dist -type f | grep $ARCH`; do mv -v $i /opt/rust-tools/bin/; done
RUN chmod 755 /opt/rust-tools/bin/*

FROM busybox
COPY --from=builder /opt/rust-tools/bin/ /opt/rust-tools/bin/
