name: build

on:
  push:

jobs:
  build:
    name: build binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "linux/arm/v7"
          - "linux/amd64"
        tool:
          - zoxide

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: prepare buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - name: get the version
        id: container
        uses: qmx/ghaction-container-tag@master

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: convert the arch
        id: sane_arch
        uses: qmx/ghaction-docker-arch@master
        with:
          docker_arch: "${{ matrix.target }}"

      - name: build
        run: docker buildx build --platform "${{ matrix.target }}" -t "qmxme/base-tools:${{ matrix.tool }}-${{ steps.sane_arch.outputs.arch }}-${{ steps.container.outputs.version }}" --push --build-arg "CRATE=${{ matrix.tool }}" .

      - name: extract binary
        run: |
          id=$(docker create "qmxme/base-tools:${{ matrix.tool }}-${{ steps.sane_arch.outputs.arch }}-${{ steps.container.outputs.version }}")
          docker cp "$id:/opt/rust-tools/bin" dist

      - name: upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: "dist/${{ matrix.tool }}-${{ steps.sane_arch.outputs.arch }}"
          path: "dist/${{ matrix.tool }}"
