name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build images and push
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: prepare buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - name: get the version
        id: container
        uses: qmx/ghaction-container-tag@master

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build and push latest
        run: docker buildx build --platform linux/amd64,linux/arm/v7 --push -t "qmxme/base-tools:${{ steps.container.outputs.version }}" .
        
