name: build

on:
  push:

jobs:
  build:
    name: build binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "linux/amd64"
          - "linux/arm/v7"
        tool:
          - cargo-bloat
          - cargo-bundle
          - cargo-docserver
          - cargo-edit
          - cargo-expand
          - cargo-release
          - cargo-tree
          - cargo-watch
          - cargo-web
          - cpubars
          - diesel_cli
          - sccache
          - starship
          - wasm-pack
          - wk
          - zoxide

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: prepare buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.3.1

      - name: get the version
        id: container
        uses: qmx/ghaction-container-tag@master

      - name: convert the arch
        id: sane_arch
        uses: qmx/ghaction-docker-arch@master
        with:
          docker_arch: "${{ matrix.target }}"

      - name: build
        run: docker buildx build --platform "${{ matrix.target }}" -t "qmxme/base-tools:${{ matrix.tool }}-${{ steps.sane_arch.outputs.arch }}-${{ steps.container.outputs.version }}" --load --build-arg "CRATE=${{ matrix.tool }}" .

      - name: extract binary
        shell: bash
        run: |
          id=$(docker create "qmxme/base-tools:${{ matrix.tool }}-${{ steps.sane_arch.outputs.arch }}-${{ steps.container.outputs.version }}")
          echo $id
          docker cp "$id:/opt/rust-tools/bin" dist

      - name: upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: "${{ steps.sane_arch.outputs.arch }}/${{ matrix.tool }}"
          path: "dist"

  package:
    name: package binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "linux/amd64"
          - "linux/arm/v7"
    needs: ['build']
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: download artifacts
        uses: actions/download-artifact@v2-preview
        with:
          path: dist/

      - name: list artifacts
        run: ls -lR dist

      - name: get the version
        id: container
        uses: qmx/ghaction-container-tag@master

      - name: convert the arch
        id: sane_arch
        uses: qmx/ghaction-docker-arch@master
        with:
          docker_arch: "${{ matrix.target }}"

      - name: build image
        run : docker build --build-arg "ARCH=${{ steps.sane_arch.outputs.arch }}" -t "qmxme/base-tools:${{ steps.container.outputs.version }}-${{ steps.sane_arch.outputs.arch }}" -f Dockerfile.dist .

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: push to dockerhub
        run: docker push "qmxme/base-tools:${{ steps.container.outputs.version }}-${{ steps.sane_arch.outputs.arch }}"
