name: build

on:
  push:

jobs:
  build:
    name: build binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "linux/arm/v7"
          - "linux/amd64"
        tool:
          - zoxide

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: prepare buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - name: get the version
        id: container
        uses: qmx/ghaction-container-tag@master

      - name: login to docker hub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "qmx" --password-stdin

      - name: convert the arch
        id: sane_arch
        uses: qmx/ghaction-docker-arch@master
        with:
          docker_arch: "${{ matrix.target }}"

      - name: build
        run: docker buildx build --platform "${{ matrix.target }}" -t "docker.pkg.github.com/qmx/docker-base-tools/${{ matrix.tool }}:${{ sane_arch.outputs.arch }}-${{ steps.container.outputs.version }}" --push --build-arg "CRATE=${{ matrix.tool }}" .
        
